describe("my_story", function ()

  -- beforeAll(function () end)
  -- beforeEach(function () end)
  -- afterAll(function () end)
  -- afterEach(function () end) 

  it('not runs', function ()
    expect(40).toBe(42)
  end)

  describe("my_nested_story_1", function ()
    it('runs', function ()
      expect(42).toBe(42)
    end)
    it('not runs', function ()
      expect("toto").toBe("tata")
    end)
    it('runs', function ()
      expect(42).toBe(42)
    end)
    it('runs', function ()
      expect(42).toBe(42)
    end)
  end)

  describe("my_nested_story_2", function ()
    it('runs', function ()
      expect(42).toBe(42)
    end)
    it('runs', function ()
      expect(42).toBe(42)
    end)
    it('runs', function ()
      expect(42).toBe(42)
    end)
    it('runs', function ()
      expect(42).toBe(42)
    end)

    describe("my_nested_story_3", function ()
      describe("my_nested_story_3_1", function ()
        it('runs', function ()
          expect(42).toBe(42)
        end)
        it('runs', function ()
          expect(42).toBe(42)
        end)
        it('runs', function ()
          expect(42).toBe(42)
        end)
        it('runs', function ()
          expect(42).toBe(42)
        end)
      end)

      it('runs', function ()
        expect(42).toBe(42)
      end)
      it('runs', function ()
        expect(42).toBe(42)
      end)
      it('runs', function ()
        expect(42).toBe(42)
      end)
      it('runs', function ()
        expect(42).toBe(42)
      end)
    end)

    describe("my_nested_story_4", function ()
      it('runs', function ()
        expect(42).toBe(42)
      end)
      it('runs', function ()
        expect(42).toBe(42)
      end)
      it('runs', function ()
        expect(42).toBe(42)
      end)
      it('runs', function ()
        expect(42).toBe(42)
      end)
    end)
  end)
end)

describe("my_other_story", function ()
  it('runs', function ()
    expect(42).toBe(42)
  end)
  it('runs', function ()
    expect(42).toBe(42)
  end)
  it('runs', function ()
    expect(42).toBe(42)
  end)
end)
