it("breaks", function ()
  expect(4).toBe(2)
end)

describe("my_story", function ()
  it("not runs", function ()
    expect(40).toBe(42)
  end)

  describe("my_nested_story_1", function ()
    local test_value = 0
    beforeAll(function ()
      test_value = 1
    end)

    beforeEach(function ()
      test_value = test_value + 1
    end)

    it("runs", function ()
      expect(test_value).toBe(2)
    end)
    it("not runs", function ()
      expect("toto").toBe("tata")
    end)
    it("runs", function ()
      expect(test_value).toBe(4)
    end)
    it("runs", function ()
      expect(test_value).toBe(5)
    end)
  end)

  describe("my_nested_story_2", function ()
    it("runs", function ()
      expect(42).toBe(42)
    end)
    it("runs", function ()
      expect(42).toBe(42)
    end)
    it("runs", function ()
      expect(42).toBe(42)
    end)
    it("runs", function ()
      expect(42).toBe(42)
    end)

    describe("my_nested_story_2_1", function ()
      describe("my_nested_story_2_1_1", function ()
        it("runs", function ()
          expect(42).toBe(42)
        end)
        it("runs", function ()
          expect(42).toBe(42)
        end)
        it("runs", function ()
          expect(42).toBe(42)
        end)
        it("runs", function ()
          expect(42).toBe(42)
        end)
      end)

      it("runs", function ()
        expect(42).toBe(42)
      end)
      it("runs", function ()
        expect(42).toBe(42)
      end)
      it("runs", function ()
        expect(42).toBe(42)
      end)
      it("runs", function ()
        expect(42).toBe(42)
      end)
    end)

    describe("my_nested_story_2_2", function ()
      it("runs", function ()
        expect(42).toBe(42)
      end)
      it("runs", function ()
        expect(42).toBe(42)
      end)
      it("runs", function ()
        expect(42).toBe(42)
      end)
      it("runs", function ()
        expect(42).toBe(42)
      end)
    end)
  end)
end)

describe("my_other_story", function ()
  it("runs", function ()
    expect(42).toBe(42)
  end)
  it("runs", function ()
    expect(42).toBe(42)
  end)
  it("runs", function ()
    expect(42).toBe(42)
  end)
end)
